# permissions for end users to view githubrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubrepository-viewer-role
rules:
- apiGroups:
  - github.repository.nttdata.com
  resources:
  - githubrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.repository.nttdata.com
  resources:
  - githubrepositories/status
  verbs:
  - get
