# permissions for end users to edit githubrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubrepository-editor-role
rules:
- apiGroups:
  - github.repository.nttdata.com
  resources:
  - githubrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.repository.nttdata.com
  resources:
  - githubrepositories/status
  verbs:
  - get
